"""001_initial_schema

Revision ID: 91259d91f38f
Revises: 
Create Date: 2026-03-23 11:21:23.578418

"""
from typing import Sequence, Union

from alembic import op
import pgvector.sqlalchemy.vector
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '91259d91f38f'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.execute('CREATE EXTENSION IF NOT EXISTS vector')
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('embeddings',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('entity_type', sa.String(length=50), nullable=False),
    sa.Column('entity_id', sa.UUID(), nullable=False),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=1536), nullable=False),
    sa.Column('model_id', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.CheckConstraint("entity_type IN ('memory_record', 'source_chunk')", name='ck_embeddings_entity_type'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('entity_type', 'entity_id', 'model_id', name='uq_embeddings_entity_model')
    )
    op.create_index('idx_embeddings_entity', 'embeddings', ['entity_type', 'entity_id'], unique=False)
    op.create_index('idx_embeddings_vector', 'embeddings', ['embedding'], unique=False, postgresql_using='hnsw', postgresql_with={'m': 16, 'ef_construction': 64}, postgresql_ops={'embedding': 'vector_cosine_ops'})
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('auth_provider', sa.String(length=50), nullable=False),
    sa.Column('auth_provider_id', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('display_name', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('auth_provider', 'auth_provider_id', name='uq_users_auth_provider'),
    sa.UniqueConstraint('email', name='uq_users_email')
    )
    op.create_index('idx_users_email', 'users', ['email'], unique=False)
    op.create_table('workspaces',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('owner_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_workspaces_owner_id', 'workspaces', ['owner_id'], unique=False)
    op.create_table('memory_spaces',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.CheckConstraint("status IN ('active', 'archived')", name='ck_memory_spaces_status'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_memory_spaces_status', 'memory_spaces', ['status'], unique=False)
    op.create_index('idx_memory_spaces_workspace_id', 'memory_spaces', ['workspace_id'], unique=False)
    op.create_table('generated_summaries',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('memory_space_id', sa.UUID(), nullable=False),
    sa.Column('summary_type', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('is_edited', sa.Boolean(), nullable=False),
    sa.Column('edited_content', sa.Text(), nullable=True),
    sa.Column('record_ids_used', postgresql.ARRAY(sa.UUID()), nullable=False),
    sa.Column('prompt_version', sa.String(length=100), nullable=False),
    sa.Column('model_id', sa.String(length=100), nullable=False),
    sa.Column('generated_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.CheckConstraint("summary_type IN ('one_pager', 'recent_updates')", name='ck_generated_summaries_summary_type'),
    sa.ForeignKeyConstraint(['memory_space_id'], ['memory_spaces.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_generated_summaries_memory_space_id', 'generated_summaries', ['memory_space_id'], unique=False)
    op.create_index('idx_generated_summaries_summary_type', 'generated_summaries', ['summary_type'], unique=False)
    op.create_table('memory_records',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('memory_space_id', sa.UUID(), nullable=False),
    sa.Column('record_type', sa.String(length=50), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('origin', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('confidence', sa.Numeric(precision=3, scale=2), nullable=False),
    sa.Column('importance', sa.String(length=20), nullable=False),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.CheckConstraint("importance IN ('low', 'medium', 'high')", name='ck_memory_records_importance'),
    sa.CheckConstraint("origin IN ('extracted', 'manual')", name='ck_memory_records_origin'),
    sa.CheckConstraint("record_type IN ('fact', 'event', 'decision', 'issue', 'question', 'preference', 'task', 'insight')", name='ck_memory_records_record_type'),
    sa.CheckConstraint("status IN ('active', 'tentative', 'outdated', 'archived')", name='ck_memory_records_status'),
    sa.CheckConstraint('confidence >= 0.00 AND confidence <= 1.00', name='ck_memory_records_confidence'),
    sa.ForeignKeyConstraint(['memory_space_id'], ['memory_spaces.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_memory_records_memory_space_id', 'memory_records', ['memory_space_id'], unique=False)
    op.create_index('idx_memory_records_record_type', 'memory_records', ['record_type'], unique=False)
    op.create_index('idx_memory_records_status', 'memory_records', ['status'], unique=False)
    op.create_table('sources',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('memory_space_id', sa.UUID(), nullable=False),
    sa.Column('source_type', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('processing_status', sa.String(length=50), nullable=False),
    sa.Column('processing_error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.CheckConstraint("processing_status IN ('pending', 'processing', 'completed', 'failed')", name='ck_sources_processing_status'),
    sa.CheckConstraint("source_type IN ('note', 'document', 'transcript')", name='ck_sources_source_type'),
    sa.ForeignKeyConstraint(['memory_space_id'], ['memory_spaces.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_sources_memory_space_id', 'sources', ['memory_space_id'], unique=False)
    op.create_index('idx_sources_processing_status', 'sources', ['processing_status'], unique=False)
    op.create_table('record_source_links',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('record_id', sa.UUID(), nullable=False),
    sa.Column('source_id', sa.UUID(), nullable=False),
    sa.Column('evidence_text', sa.Text(), nullable=True),
    sa.Column('evidence_start_offset', sa.Integer(), nullable=True),
    sa.Column('evidence_end_offset', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['record_id'], ['memory_records.id'], ),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('record_id', 'source_id', name='uq_record_source_links_record_source')
    )
    op.create_index('idx_record_source_links_record_id', 'record_source_links', ['record_id'], unique=False)
    op.create_index('idx_record_source_links_source_id', 'record_source_links', ['source_id'], unique=False)
    op.create_table('source_chunks',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('source_id', sa.UUID(), nullable=False),
    sa.Column('chunk_index', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('start_offset', sa.Integer(), nullable=False),
    sa.Column('end_offset', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_id', 'chunk_index', name='uq_source_chunks_source_chunk_index')
    )
    op.create_index('idx_source_chunks_source_id', 'source_chunks', ['source_id'], unique=False)
    op.create_table('source_contents',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('source_id', sa.UUID(), nullable=False),
    sa.Column('content_text', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_id')
    )
    op.create_table('source_files',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('source_id', sa.UUID(), nullable=False),
    sa.Column('file_path', sa.String(length=1000), nullable=False),
    sa.Column('mime_type', sa.String(length=100), nullable=False),
    sa.Column('size_bytes', sa.BigInteger(), nullable=False),
    sa.Column('original_filename', sa.String(length=500), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('source_files')
    op.drop_table('source_contents')
    op.drop_index('idx_source_chunks_source_id', table_name='source_chunks')
    op.drop_table('source_chunks')
    op.drop_index('idx_record_source_links_source_id', table_name='record_source_links')
    op.drop_index('idx_record_source_links_record_id', table_name='record_source_links')
    op.drop_table('record_source_links')
    op.drop_index('idx_sources_processing_status', table_name='sources')
    op.drop_index('idx_sources_memory_space_id', table_name='sources')
    op.drop_table('sources')
    op.drop_index('idx_memory_records_status', table_name='memory_records')
    op.drop_index('idx_memory_records_record_type', table_name='memory_records')
    op.drop_index('idx_memory_records_memory_space_id', table_name='memory_records')
    op.drop_table('memory_records')
    op.drop_index('idx_generated_summaries_summary_type', table_name='generated_summaries')
    op.drop_index('idx_generated_summaries_memory_space_id', table_name='generated_summaries')
    op.drop_table('generated_summaries')
    op.drop_index('idx_memory_spaces_workspace_id', table_name='memory_spaces')
    op.drop_index('idx_memory_spaces_status', table_name='memory_spaces')
    op.drop_table('memory_spaces')
    op.drop_index('idx_workspaces_owner_id', table_name='workspaces')
    op.drop_table('workspaces')
    op.drop_index('idx_users_email', table_name='users')
    op.drop_table('users')
    op.drop_index('idx_embeddings_vector', table_name='embeddings', postgresql_using='hnsw', postgresql_with={'m': 16, 'ef_construction': 64}, postgresql_ops={'embedding': 'vector_cosine_ops'})
    op.drop_index('idx_embeddings_entity', table_name='embeddings')
    op.drop_table('embeddings')
    # ### end Alembic commands ###
